# Docker Compose
version: '3.9'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend
    restart: unless-stopped
    # networks:
    #   - app-net
    env_file:
      - .env

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    # networks:
    #   - app-net
    env_file:
      - .env

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
        - 11434:11434
    volumes:
        - ./ollama/ollama:/root/.ollama
        - ./entrypoint.sh:/entrypoint.sh
        - ollama_data:/ollama/data
    pull_policy: always
    tty: true
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    restart: unless-stopped
    # networks:
    #   - app-net
    env_file:
      - .env

volumes:
  ollama_data:
# networks:
#   app-net:
#     driver: bridge